### ISSUE TITLE
TS files produced have significant audio issues

### ISSUE THREAD

**Issue by tt2468** [wmw9/rekoda#2]
I've been having audio issues with streamlink too, but I'm desperately looking for an answer. Vods being recorded have severe audio cuts, or have audio which is slow and desynced. See https://tt2468.net/dl/paymoneywubby_2022-01-17_01-33-30.ts for an example.

When I first used this over a week ago, everything seemed to be okay, but something must have changed and now everything is broken.

Edit: Played with VLC

**Comment by tt2468** [comment]
Definitely twitch's fault. Using the ffmpeg command `ffmpeg -i in.ts -c:a aac -c:v copy out.mp4` fixes the issue

**Comment by evan-sm** [comment]
Yes, I'm aware of that VLC sound issue (flickering). It works fine using another player like mpv. Also, if you upload that "broken" .ts to youtube it is also fine.

So this issue is not high priority, definitely something wrong with .ts container and the way chunks being joined into a file.

`ffmpeg -i in.ts` gives some warning messages about audio. Will look at it later.
